apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hooks-demo
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/kirshiyin89/argocd-hook-demo
    targetRevision: HEAD
    path: app/jobs
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
     # selfHeal: true
    syncOptions:
    - ApplyOutOfSyncOnly=true
    - Replace=true


