apiVersion: v1
kind: ConfigMap
metadata:
  name: version-tracker
data:
  counter: "2"
---
apiVersion: batch/v1
kind: Job
metadata:
  name: cache-warmer
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/sync-options: Replace=true,Force=true
    argocd.argoproj.io/hook-delete-policy: HookBeforeCreation
spec:
  backoffLimit: 0
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: warmer
        image: curlimages/curl:latest
        command:
        - /bin/sh
        - -c
        - |
          echo "Starting cache warming...."
          # Your cache warming logic
          echo "Cache warming completed, logs being shipped..."
