apiVersion: v1
kind: ConfigMap
metadata:
  name: version-tracker
data:
  counter: "1"  # Change this to trigger new syncs
---
apiVersion: batch/v1
kind: Job
metadata:
  name: cache-warmer
  annotations:
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
    argocd.argoproj.io/sync-options: Replace=true
spec:
  template:
    metadata:
      name: cache-warmer
    spec:
      restartPolicy: Never
      containers:
      - name: warmer
        image: curlimages/curl:latest
        command:
        - /bin/sh
        - -c
        - |
          echo "Done cache warming"
          
          echo "Cache warming completed successfully!"
