apiVersion: v1
kind: ConfigMap
metadata:
  name: version-tracker
data:
  counter: "2"
---
apiVersion: batch/v1
kind: Job
metadata:
  name: cache-warmer
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded, HookFailed
spec:
  backoffLimit: 0
  template:
    metadata:
      name: cache-warmer
    spec:
      restartPolicy: Never
      containers:
      - name: warmer
        image: curlimages/curl:latest
        command:
        - /bin/sh
        - -c
        - |
          echo "Starting cache warming...."
          
          # Wait for service with 5 second timeout
          echo "Checking if simple-app-service is available (5 second timeout)..."
      #    if ! curl -f --connect-timeout 5 --max-time 5 http://simple-app-service/health; then
     #       echo "ERROR: simple-app-service is not available within 5 seconds"
     #       echo "Cache warming failed - service not ready"
     #       exit 1
     #     fi
        
