apiVersion: v1
kind: ConfigMap
metadata:
  name: version-tracker
data:
  counter: "1"
---
apiVersion: batch/v1
kind: Job
metadata:
  name: cache-warmer
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    argocd.argoproj.io/sync-options: Replace=true
 #   argocd.argoproj.io/hook: PostSync
 #   argocd.argoproj.io/hook-delete-policy: HookSucceeded, HookFailed
spec:
  backoffLimit: 0
  template:
    metadata:
      name: cache-warmer
    spec:
      restartPolicy: Never
      containers:
      - name: warmer
        image: curlimages/curl:latest
        command:
        - /bin/sh
        - -c
        - |
          echo "Starting cache warming....."
          
          # Wait for service with 5 second timeout

          
          echo "Service is ready! Proceeding with cache warming..."
          echo "Warming cache for home page..."
          curl -s http://simple-app-service/ > /dev/null
          
          echo "Warming cache for API endpoint..."
          curl -s http://simple-app-service/api/data > /dev/null
          
          echo "Cache warming completed successfully!"
