apiVersion: v1
kind: ConfigMap
metadata:
  name: version-tracker
data:
  counter: "2"
---
apiVersion: batch/v1
kind: Job
metadata:
  name: cache-warmer
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  backoffLimit: 0
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: warmer
        image: curlimages/curl:latest
        command:
        - /bin/sh
        - -c
        - |
          echo "Starting cache warming...."
          # Your cache warming logic
          echo "Cache warming completed, logs being shipped..."
          sleep 25  # Fluentd shipping window
---
apiVersion: batch/v1
kind: Job
metadata:
  name: cache-warmer-cleanup
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-weight: "1"  # Runs after cache-warmer
    argocd.argoproj.io/hook-delete-policy: HookSucceeded, HookFailed
spec:
  backoffLimit: 0
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: cleanup
        image: curlimages/curl:latest
        command: ["echo", "Cleanup placeholder - logs should be shipped by now"]
