apiVersion: v1
kind: ConfigMap
metadata:
  name: version-tracker
data:
  counter: "1"
---
apiVersion: batch/v1
kind: Job
metadata:
  name: cache-warmer
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    argocd.argoproj.io/hook-delete-policy: HookBeforeCreation
spec:
  backoffLimit: 0
  template:
    metadata:
      name: cache-warmer
    spec:
      restartPolicy: Never
      containers:
      - name: warmer
        image: curlimages/curl:latest
        command:
        - /bin/sh
        - -c
        - |
          echo "Starting cache warming...."
