apiVersion: v1
kind: ServiceAccount
metadata:
  name: job-manager
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: job-manager
rules:
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: job-manager
subjects:
- kind: ServiceAccount
  name: job-manager
roleRef:
  kind: Role
  name: job-manager
  apiGroup: rbac.authorization.k8s.io
