apiVersion: batch/v1
kind: Job
metadata:
  generateName: standalone-job-
  annotations:
    argocd.argoproj.io/sync-options: Force=true
spec:
  template:
  #  metadata:
 #     labels:
 #       job-name: standalone-job
    spec:
      restartPolicy: Never
      containers:
      - name: standalone
        image: curlimages/curl:latest
        command:
        - /bin/sh
        - -c
        - |
          echo "Started job."
